#!/bin/bash

# add the dce-examples dir to your .bashrc file to be able to call this from anywhere 

# run this script in your test dir (where your index.js file is)
# to instrument the index.js file using Wasabi 
# pass in the path for the dir that contains the .wasm file to be instrumented 
# NOTE: do not pass in the .wasm file path, 
# just the path of the directory containing it 

# $1 has path to wasm file to instrument 
# raise error if not passed 
if [ -z "$1"]
then 
    echo "Pass in path to the directory with .wasm file to be instrumented."
    exit 1 
fi

# save the path to the test  
curr_path=`pwd`

# cd into directory with the wasm file we want to instrument 
cd $1 

# save the name of the wasmfile we want to instrument and instrument it 
wasm_file=`find . -maxdepth 1 -type f -name "*.wasm"`
wasabi --node --hooks=begin,call,store $wasm_file

# create new directory to save the original wasm file 
mkdir org-wasm 
mv "$wasm_file" "org-wasm/"

# move all files in the out folder generated by wasabi into the dir one level above  
mv -v ./out/* . > /dev/null

# save the full path of the wasabi file - we want to use it in our instrumented js file 
wasabi_file=`find . -maxdepth 1 -type f -name "*.wasabi.js"`
wasabi_file=`realpath $wasabi_file`

# cd to the test directory again 
cd $curr_path

# create instrumented file 
echo "const fs = require(\"fs\");
global.Wasabi = require(\"$wasabi_file\");

let analysis = require(\"./../../analysis.js\");
" > instrumented-index.js

cat index.js >> instrumented-index.js

echo "require('./../../collect-data.js')" >> instrumented-index.js